version: '3.9'
services:
  app3:
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
    #command: tail -f /dev/null
    image: app3-carprediction:new
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8000:80"
    volumes:
      - ./app3:/root/app3
      - ./.vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
    env_file:
      - .env

volumes:
 vscode-server: